[auth]
admin_email = "admin@gmail.com"
allowed_user = "admin@example.com"  # update to the user you want to allow

[crypto]
aes_key_b64 = "mZ8W9q3iV9QkL6rQxMvFj2NQpR0uT9wB8p3LqZlM2a4="  # make sure this is a valid 32-byte Base64 key
